### ISSUE TITLE
Include repo in chery pick output

### ISSUE THREAD

**Issue by domcleal** [ehelms/tool_belt#11]
The cherry picks file doesn't specify which repositories the SHAs should be cherry picked in, so either splitting it up per repo or listing it somehow would be very useful.

**Comment by ehelms** [comment]
I looked into this a bit and there isn't a straightforward solution because Redmine doesn't return the repository associated to the changeset in the response, however I do have 3 ideas.

1) Use the project and category information that already exists in the issue which would produce something like:

```
9539 - 2015-02-25 15:01:51 UTC: Katello:Docker ["1c977c92600bd4240523a2709846c4f2fa27e7f0"] app/models/repository_docker_image.rb is in the wrong directory and is not being used
```

2) Modify Redmine to include the repository information when asking the issues API for changesets. This could be done both to upstream Redmine and a local patch.

3) Create local copies of each repository specified int he configuration in a 'build' directory that are set to master and then scan those repositories for a given hash to locate the repository a cherry pick lives in.

**Comment by domcleal** [comment]
(3) is probably possible even with the checked out stable branches, as the clone ought to fetch all remote refs.
