### ISSUE TITLE
Include older releases when cherry picking for a release

### ISSUE THREAD

**Issue by domcleal** [ehelms/tool_belt#15]
I'd like to be able to verify that tickets from (certain?) older releases are still included when cherry picking.  In particular, currently Foreman is working on release 1.10.0 (ID 63) but simultaneously 1.9.2 (ID 88) and 1.9.3 (ID 91) have been released.

Since a ticket can only be assigned to one release, I'd normally search for tickets assigned to any of 1.10.0, 1.9.3 or 1.9.2 when cherry picking for 1.10.0.  For 1.10.1, I'd probably search for 1.10.1 and 1.9.3 and 1.9.4.

It might be sufficient to be able to specify multiple redmine_release_ids per release and leave it up to the user.

**Comment by ehelms** [comment]
@domcleal I believe https://github.com/ehelms/tool_belt/pull/32 will address this. The PR takes the tactic of having the user specify the prior releases to investigate instead of trying to use some method like config file inspection or querying Redmine for all releases to do it. Let me know if that appears sufficient for you.
